### PR TITLE
Update GHA release pipeline & service owners

### PR DESCRIPTION
**Pull request by cmharlow**
Jira ticket: came up in context of https://mozilla-hub.atlassian.net/browse/SE-2244

What this PR does:
* implements deduped github actions stage & prod release workflows
* adds determined service owner to contribute page

### CODE REVIEW

**Comment by cmharlow** [comment]
Tagging @bkochendorfer so he can see the changes to GHA workflow from moderator work.

**Comment by cmharlow** [comment]
will investigate CI error in a bit.

**Comment by anewuser** [comment]
@cmharlow you've disabled the "Issues" tab of this repository, so I'm leaving a comment here.

https://pastebin.mozilla.org/ currently sets the paste to expire in one hour by default.

Because of this, forums such as /r/Firefox tell people to use third-party services instead to upload their `about:support` data, since reminding users to change the expiration date would add friction to the process. 

Could you please change it to expire in `21 days` by default?

**Comment by anewuser** [comment]
@bkochendorfer please read the above comment.

**Comment by phammer-sre** [comment]
@anewuser there are a number of implications to changing the default expiry. We'd prefer at this time if the advice in the forums is what you followed

**Comment by anewuser** [comment]
@bkochendorfer @phammer-sre  I didn't follow any advice. I provide support to other users.

Sometimes it's necessary to ask them to paste some information, and then other users providing support link to Pastebin or similar third-party sites, which save the pastes permanently by default.

If you're concerned about people's privacy, you'll agree with me that using a Mozilla service will be better than Pastebin or another random site. 

However, asking them to change the expiration time manually, so that there will be enough time for us to see the paste and examine it, adds friction to the process. It might take hours until a volunteer opens the page again and sees the reply with the link.

That's why I came here to ask you to change the default time, so that everyone providing support will agree that it is a good alternative to Pastebin. I said `21 days` but I actually meant just `1 day`, or at least a few hours.

**Comment by phammer-sre** [comment]
Hi @anewuser I appreciate the feedback. At this time, we are only providing security updates to pastebin. We will make a note of this default expiry concern. If the current stance changes, we will have a record of this use case to look into. Once again, I thank you for your support and recommend continuing with the current workaround to this use case.

**Comment by anewuser** [comment]
Unfortunately, the moderators of /r/Firefox have informed me that they'll keep pointing people to a third-party site as long as your default time is just 1 hour. That's good enough for a chat, but not for a forum where people aren't online all the time. Personally, I'd just ask everyone to change the time manually. The moderators were the ones who called it "adding friction."

Anyway, thank you,

**Pull request merged**
